### ISSUE TITLE
api-platform json-ld PUT request error

### ISSUE THREAD

**Issue by huynguyen93** [cleverage/eav-manager#47]
Hello, I have an error with json-ld PUT request. It seems that `id` format `/api/resouces/{id}` is not handled.

My request:
![Screenshot from 2019-11-19 10-15-41](https://user-images.githubusercontent.com/16201014/69114346-ad3d7380-0ab7-11ea-9244-41a174a03bb1.png)

From the exception stack trace: I tried to debug:
![Screenshot from 2019-11-19 10-18-33](https://user-images.githubusercontent.com/16201014/69114387-c8a87e80-0ab7-11ea-8fdd-0260593b277d.png)

and here is where the untranslated `id` is used to search for the entity
![Screenshot from 2019-11-19 10-19-44](https://user-images.githubusercontent.com/16201014/69114453-f55c9600-0ab7-11ea-9c58-297f20ec5e62.png)

This is the stack trace:
![Screenshot from 2019-11-19 10-26-01](https://user-images.githubusercontent.com/16201014/69114457-fd1c3a80-0ab7-11ea-93f4-207c7a46896d.png)

Thank you!

**Comment by shavounet** [comment]
I've checked your `composer.lock` file an I think you're missing 2 useful commits 
* VincentChalnot/SidusEAVModelBundle@34d783d764e6a862e02d052cb2f29156db416783
* VincentChalnot/SidusEAVModelBundle@16b17ec41ae73d5d50aae52e48ec2cdc3b120d8a

Try to update, it should fix your problem.
