### ISSUE TITLE
Data in the data collector are broken

### ISSUE THREAD

**Issue by johnkrovitch** [cleverage/eav-manager#71]
Data in the data collector are broken. There is too much data in the family registry which an error in the serialization.

**Comment by johnkrovitch** [comment]
In the last version, an error occurred in the data tabs in the profiler :
An exception has been thrown during the rendering of a template ("Notice: Undefined index: nodes").

**Comment by VincentChalnot** [comment]
Fixed in v1.3.8

**Comment by VincentChalnot** [comment]
Maybe not...
